# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_pityna.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidgetLog = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetLog.setGeometry(QtCore.QRect(5, 0, 340, 500))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidgetLog.setFont(font)
        self.listWidgetLog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidgetLog.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidgetLog.setObjectName("listWidgetLog")
        self.radioButton1 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton1.setGeometry(QtCore.QRect(30, 510, 130, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton1.setFont(font)
        self.radioButton1.setChecked(True)
        self.radioButton1.setObjectName("radioButton1")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(200, 510, 130, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(5, 540, 680, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.buttonTalk = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTalk.setGeometry(QtCore.QRect(690, 540, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonTalk.setFont(font)
        self.buttonTalk.setObjectName("buttonTalk")
        self.labelResponce = QtWidgets.QLabel(self.centralwidget)
        self.labelResponce.setGeometry(QtCore.QRect(350, 300, 500, 200))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelResponce.setFont(font)
        self.labelResponce.setFrameShape(QtWidgets.QFrame.Box)
        self.labelResponce.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelResponce.setText("")
        self.labelResponce.setAlignment(QtCore.Qt.AlignCenter)
        self.labelResponce.setObjectName("labelResponce")
        self.labelShowlmg = QtWidgets.QLabel(self.centralwidget)
        self.labelShowlmg.setGeometry(QtCore.QRect(350, 0, 501, 301))
        self.labelShowlmg.setText("")
        self.labelShowlmg.setPixmap(QtGui.QPixmap(":/re/img1.gif"))
        self.labelShowlmg.setObjectName("labelShowlmg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuClose = QtWidgets.QAction(MainWindow)
        self.menuClose.setObjectName("menuClose")
        self.menu.addAction(self.menuClose)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.buttonTalk.clicked.connect(MainWindow.buttonTalkSlot) # type: ignore
        self.radioButton1.clicked.connect(MainWindow.showResponderName) # type: ignore
        self.radioButton_2.clicked.connect(MainWindow.hiddenResponderName) # type: ignore
        self.menuClose.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton1.setText(_translate("MainWindow", "Responder"))
        self.radioButton_2.setText(_translate("MainWindow", "Responder"))
        self.buttonTalk.setText(_translate("MainWindow", "話す"))
        self.menu.setTitle(_translate("MainWindow", "ファイル"))
        self.menuClose.setText(_translate("MainWindow", "閉じる"))
import qt_resource_rc
